CREATE TABLE IF NOT EXISTS category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(120)                            NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT pk_category PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(160)                            NOT NULL,
    description VARCHAR(2000),
    price       DECIMAL(14, 2)                          NOT NULL,
    sku         VARCHAR(64)                             NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT ck_product_price_non_negative CHECK (price >= 0)
    );

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

ALTER TABLE product
    ADD CONSTRAINT uc_product_sku UNIQUE (sku);

CREATE INDEX idx_product_name ON product (name);
CREATE INDEX idx_product_category_id ON product (category_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);